"""Add verification_token to submission_metadata

Revision ID: 15ea159823d1
Revises: 0e11bbbf6106
Create Date: 2026-03-17 09:44:53.922941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ea159823d1'
down_revision: Union[str, None] = '0e11bbbf6106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_submission_metadata_verification_token'), ['verification_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_metadata_verification_token'))
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
