"""Add parse_feedback to submission_metadata

Revision ID: 175f737df241
Revises: 3fc734eb14f2
Create Date: 2026-03-27 10:47:43.639100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175f737df241'
down_revision: Union[str, None] = '3fc734eb14f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.drop_column('parse_feedback')

    # ### end Alembic commands ###
