"""Add email verification columns to submission_metadata

Revision ID: 3fc734eb14f2
Revises: 15ea159823d1
Create Date: 2026-03-24 22:09:18.820308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc734eb14f2'
down_revision: Union[str, None] = '15ea159823d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('token_expires_at')

    # ### end Alembic commands ###
