"""Add status columns and submission_metadata tables

Revision ID: 51fb750ab3eb
Revises: cf76f64484a2
Create Date: 2026-03-16 14:10:17.190575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fb750ab3eb'
down_revision: Union[str, None] = 'cf76f64484a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_name', sa.String(length=200), nullable=False),
    sa.Column('submitter_email', sa.String(length=200), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verification_info', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('editor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_metadata_id'), ['id'], unique=False)

    op.create_table('submission_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_records_id'), ['id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_id')

    op.drop_table('submissions')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    with op.batch_alter_table('lineage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('lineage', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submitter_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('submitter_email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('submission_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('student_name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('institution_name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('relationship_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_year', sa.INTEGER(), nullable=True),
    sa.Column('end_year', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('verification_info', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('editor_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_id', ['id'], unique=False)

    with op.batch_alter_table('submission_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_records_id'))

    op.drop_table('submission_records')
    with op.batch_alter_table('submission_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_metadata_id'))

    op.drop_table('submission_metadata')
    # ### end Alembic commands ###
