"""initial schema

Revision ID: cf76f64484a2
Revises: 
Create Date: 2026-03-11 17:26:20.701750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf76f64484a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_id'), ['id'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_id'), ['id'], unique=False)

    op.create_table('musicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.String(length=50), nullable=True),
    sa.Column('death_date', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('bio_notes', sa.Text(), nullable=True),
    sa.Column('name_search', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_musicians_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_musicians_name_search'), ['name_search'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_id'), ['id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_name', sa.String(length=200), nullable=False),
    sa.Column('submitter_email', sa.String(length=200), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=False),
    sa.Column('teacher_name', sa.String(length=300), nullable=True),
    sa.Column('student_name', sa.String(length=300), nullable=True),
    sa.Column('institution_name', sa.String(length=300), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verification_info', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('editor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_id'), ['id'], unique=False)

    op.create_table('institution_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_names_id'), ['id'], unique=False)

    op.create_table('lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['musicians.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['musicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'student_id', 'institution_id', name='uq_lineage_teacher_student_institution')
    )
    with op.batch_alter_table('lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_id'), ['id'], unique=False)

    op.create_table('musician_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['musician_id'], ['musicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('musician_instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_musician_instruments_id'), ['id'], unique=False)

    op.create_table('musician_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('name_search', sa.String(length=400), nullable=True),
    sa.Column('name_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['musician_id'], ['musicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('musician_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_musician_names_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_musician_names_name_search'), ['name_search'], unique=False)

    op.create_table('lineage_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineage_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('page_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lineage_id'], ['lineage.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lineage_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_sources_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineage_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_sources_id'))

    op.drop_table('lineage_sources')
    with op.batch_alter_table('musician_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_musician_names_name_search'))
        batch_op.drop_index(batch_op.f('ix_musician_names_id'))

    op.drop_table('musician_names')
    with op.batch_alter_table('musician_instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_musician_instruments_id'))

    op.drop_table('musician_instruments')
    with op.batch_alter_table('lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_id'))

    op.drop_table('lineage')
    with op.batch_alter_table('institution_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_names_id'))

    op.drop_table('institution_names')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_id'))

    op.drop_table('sources')
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_musicians_name_search'))
        batch_op.drop_index(batch_op.f('ix_musicians_id'))

    op.drop_table('musicians')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_id'))

    op.drop_table('instruments')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_id'))

    op.drop_table('institutions')
    # ### end Alembic commands ###
